// definitely ripped from https://gist.github.com/MathewReiss/20a58ad5c1bc9a6bc23b#file-phone-js-L9-L163
var grass = "grass", water = "water", fire = "fire", bug = "bug",
  psychic = "psychic", flying = "flying", ghost = "ghost", fighting = "fighting",
  normal = "normal", poison = "poison", electric = "electric", ground = "ground",
  fairy = "fairy", rock = "rock", ice = "ice", dragon = "dragon";

export const Site = [
  { name : "Bulbasaur", type : grass, stage : 0, clicked : 0, species : "Seed Site"},
  { name : "Ivysaur", type : grass, stage : 3, clicked : 0, species : "Seed Site"},
  { name : "Venusaur", type : grass, stage : 5, clicked : 0, species : "Seed Site"},
  { name : "Charmander", type : fire, stage : 0, clicked : 0, species : "Lizard Site"},
  { name : "Charmeleon", type : fire, stage : 3, clicked : 0, species : "Flame Site"},
  { name : "Charizard", type : fire, stage : 5, clicked : 0, species : "Flame Site"},
  { name : "Squirtle", type : water, stage : 0, clicked : 0, species : "Tiny Turtle Site"},
  { name : "Wartortle", type : water, stage : 3, clicked : 0, species : "Turtle Site"},
  { name : "Blastoise", type : water, stage : 5, clicked : 0, species : "Shellfish Site"},
  { name : "Caterpie", type : bug, stage : 1, clicked : 0, species : "Worm Site"},
  { name : "Metapod", type : bug, stage : 2, clicked : 0, species : "Cocoon Site"},
  { name : "Butterfree", type : bug, stage : 4, clicked : 0, species : "Butterfly Site"},
  { name : "Weedle", type : bug, stage : 1, clicked : 0, species : "Hairy Bug Site"},
  { name : "Kakuna", type : bug, stage : 2, clicked : 0, species : "Cocoon Site"},
  { name : "Beedrill", type : bug, stage : 4, clicked : 0, species : "Poison Bee Site"},
  { name : "Pidgey", type : flying, stage : 1, clicked : 0, species : "Tiny Bird Site"},
  { name : "Pidgeotto", type : flying, stage : 3, clicked : 0, species : "Bird Site"},
  { name : "Pidgeot", type : flying, stage : 5, clicked : 0, species : "Bird Site"},
  { name : "Rattata", type : normal, stage : 1, clicked : 0, species : "Mouse Site"},
  { name : "Raticate", type : normal, stage : 2, clicked : 0, species : "Mouse Site"},
  { name : "Spearow", type : flying, stage : 1, clicked : 0, species : "Tiny Bird Site"},
  { name : "Fearow", type : flying, stage : 3, clicked : 0, species : "Beak Site"},
  { name : "Ekans", type : poison, stage : 1, clicked : 0, species : "Snake Site"},
  { name : "Arbok", type : poison, stage : 3, clicked : 0, species : "Cobra Site"},
  { name : "Pikachu", type : electric, stage : 1, clicked : 0, species : "Mouse Site"},
  { name : "Raichu", type : electric, stage : 3, clicked : 0, species : "Mouse Site"},
  { name : "Sandshrew", type : ground, stage : 1, clicked : 0, species : "Mouse Site"},
  { name : "Sandslash", type : ground, stage : 2, clicked : 0, species : "Mouse Site"},
  { name : "Nidoran F", type : poison, stage : 1, clicked : 0, species : "Poison Pin Site"},
  { name : "Nidorina", type : poison, stage : 2, clicked : 0, species : "Poison Pin Site"},
  { name : "Nidoqueen", type : poison, stage : 5, clicked : 0, species : "Drill Site"},
  { name : "Nidoran M", type : poison, stage : 1, clicked : 0, species : "Poison Pin Site"},
  { name : "Nidorino", type : poison, stage : 2, clicked : 0, species : "Poison Pin Site"},
  { name : "Nidoking", type : poison, stage : 5, clicked : 0, species : "Drill Site"},
  { name : "Clefairy", type : fairy, stage : 1, clicked : 0, species : "Fairy Site"},
  { name : "Clefable", type : fairy, stage : 3, clicked : 0, species : "Fairy Site"},
  { name : "Vuplix", type : fire, stage : 1, clicked : 0, species : "Fox Site"},
  { name : "Ninetales", type : fire, stage : 3, clicked : 0, species : "Fox Site"},
  { name : "Jigglypuff", type : fairy, stage : 1, clicked : 0, species : "Balloon Site"},
  { name : "Wigglytuff", type : fairy, stage : 3, clicked : 0, species : "Balloon Site"},
  { name : "Zubat", type : poison, stage : 1, clicked : 0, species : "Bat Site"},
  { name : "Golbat", type : poison, stage : 2, clicked : 0, species : "Bat Site"},
  { name : "Oddish", type : grass, stage : 1, clicked : 0, species : "Weed Site"},
  { name : "Gloom", type : grass, stage : 2, clicked : 0, species : "Weed Site"},
  { name : "Vileplume", type : grass, stage : 3, clicked : 0, species : "Flower Site"},
  { name : "Paras", type : bug, stage : 1, clicked : 0, species : "Mushroom Site"},
  { name : "Parasect", type : bug, stage : 2, clicked : 0, species : "Mushroom Site"},
  { name : "Venonat", type : bug, stage : 1, clicked : 0, species : "Insect Site"},
  { name : "Venomoth", type : bug, stage : 2, clicked : 0, species : "Poison Moth Site"},
  { name : "Diglett", type : ground, stage : 1, clicked : 0, species : "Mole Site"},
  { name : "Dugtrio", type : ground, stage : 2, clicked : 0, species : "Mole Site"},
  { name : "Meowth", type : normal, stage : 1, clicked : 0, species : "Scratch Cat Site"},
  { name : "Persian", type : normal, stage : 2, clicked : 0, species : "Classy Cat Site"},
  { name : "Psyduck", type : water, stage : 1, clicked : 0, species : "Duck Site"},
  { name : "Golduck", type : water, stage : 2, clicked : 0, species : "Duck Site"},
  { name : "Mankey", type : fighting, stage : 1, clicked : 0, species : "Pig Monkey Site"},
  { name : "Primeape", type : fighting, stage : 2, clicked : 0, species : "Pig Monkey Site"},
  { name : "Growlithe", type : fire, stage : 1, clicked : 0, species : "Puppy Site"},
  { name : "Arcanine", type : fire, stage : 2, clicked : 0, species : "Legendary Site"},
  { name : "Poliwag", type : water, stage : 1, clicked : 0, species : "Tadpole Site"},
  { name : "Poliwhirl", type : water, stage : 2, clicked : 0, species : "Tadpole Site"},
  { name : "Poliwrath", type : water, stage : 5, clicked : 0, species : "Tadpole Site"},
  { name : "Abra", type : psychic, stage : 1, clicked : 0, species : "Psi Site"},
  { name : "Kadabra", type : psychic, stage : 2, clicked : 0, species : "Psi Site"},
  { name : "Alakazam", type : psychic, stage : 5, clicked : 0, species : "Psi Site"},
  { name : "Machop", type : fighting, stage : 1, clicked : 0, species : "Superpower Site"},
  { name : "Machoke", type : fighting, stage : 2, clicked : 0, species : "Superpower Site"},
  { name : "Machamp", type : fighting, stage : 5, clicked : 0, species : "Superpower Site"},
  { name : "Bellsprout", type : grass, stage : 1, clicked : 0, species : "Flower Site"},
  { name : "Weepinbell", type : grass, stage : 3, clicked : 0, species : "Flycatcher Site"},
  { name : "Victreebel", type : grass, stage : 5, clicked : 0, species : "Flycatcher Site"},
  { name : "Tentacool", type : water, stage : 1, clicked : 0, species : "Jellyfish Site"},
  { name : "Tentacruel", type : water, stage : 3, clicked : 0, species : "Jellyfish Site"},
  { name : "Geodude", type : rock, stage : 1, clicked : 0, species : "Rock Site"},
  { name : "Graveler", type : rock, stage : 3, clicked : 0, species : "Rock Site"},
  { name : "Golem", type : rock, stage : 5, clicked : 0, species : "Megaton Site"},
  { name : "Ponyta", type : fire, stage : 2, clicked : 0, species : "Fire Horse Site"},
  { name : "Rapidash", type : fire, stage : 3, clicked : 0, species : "Fire Horse Site"},
  { name : "Slowpoke", type : water, stage : 2, clicked : 0, species : "Dopey Site"},
  { name : "Slowbro", type : water, stage : 3, clicked : 0, species : "Hermit Crab Site"},
  { name : "Magnemite", type : electric, stage : 2, clicked : 0, species : "Magnet Site"},
  { name : "Magneton", type : electric, stage : 3, clicked : 0, species : "Magnet Site"},
  { name : "Farfetch'd", type : flying, stage : 3, clicked : 0, species : "Wild Duck Site"},
  { name : "Doduo", type : flying, stage : 2, clicked : 0, species : "Twin Bird Site"},
  { name : "Dodrio", type : flying, stage : 4, clicked : 0, species : "Triple Bird Site"},
  { name : "Seel", type : water, stage : 3, clicked : 0, species : "Sea Lion Site"},
  { name : "Dewgong", type : ice, stage : 5, clicked : 0, species : "Sea Lion Site"},
  { name : "Grimer", type : poison, stage : 2, clicked : 0, species : "Sludge Site"},
  { name : "Muk", type : poison, stage : 4, clicked : 0, species : "Sludge Site"},
  { name : "Shellder", type : water, stage : 2, clicked : 0, species : "Bivalve Site"},
  { name : "Cloyster", type : ice, stage : 4, clicked : 0, species : "Bivalve Site"},
  { name : "Gastly", type : ghost, stage : 2, clicked : 0, species : "Gas Site"},
  { name : "Haunter", type : ghost, stage : 3, clicked : 0, species : "Gas Site"},
  { name : "Gengar", type : ghost, stage : 4, clicked : 0, species : "Shadow Site"},
  { name : "Onix", type : rock, stage : 3, clicked : 0, species : "Rock Snake Site"},
  { name : "Drozee", type : psychic, stage : 1, clicked : 0, species : "Hypnosis Site"},
  { name : "Hypno", type : psychic, stage : 3, clicked : 0, species : "Hypnosis Site"},
  { name : "Krabby", type : water, stage : 3, clicked : 0, species : "River Crab Site"},
  { name : "Kingler", type : water, stage : 4, clicked : 0, species : "Pincer Site"},
  { name : "Voltorb", type : electric, stage : 1, clicked : 0, species : "Ball Site"},
  { name : "Electrode", type : electric, stage : 3, clicked : 0, species : "Ball Site"},
  { name : "Exeggcute", type : grass, stage : 3, clicked : 0, species : "Egg Site"},
  { name : "Exeggutor", type : grass, stage : 5, clicked : 0, species : "Coconut Site"},
  { name : "Cubone", type : ground, stage : 3, clicked : 0, species : "Lonely Site"},
  { name : "Marowak", type : ground, stage : 4, clicked : 0, species : "Bone Keeper Site"},
  { name : "Hitmonchan", type : fighting, stage : 5, clicked : 0, species : "Kicking Site"},
  { name : "Hitmonlee", type : fighting, stage : 5, clicked : 0, species : "Punching Site"},
  { name : "Lickitung", type : normal, stage : 4, clicked : 0, species : "Licking Site"},
  { name : "Koffing", type : poison, stage : 2, clicked : 0, species : "Poison Gas Site"},
  { name : "Weezing", type : poison, stage : 4, clicked : 0, species : "Poison Gas Site"},
  { name : "Rhyhorn", type : rock, stage : 3, clicked : 0, species : "Spikes Site"},
  { name : "Rhydon", type : rock, stage : 4, clicked : 0, species : "Drill Site"},
  { name : "Chansey", type : normal, stage : 4, clicked : 0, species : "Egg Site"},
  { name : "Tangela", type : grass, stage : 4, clicked : 0, species : "Vine Site"},
  { name : "Kangaskhan", type : normal, stage : 4, clicked : 0, species : "Parent Site"},
  { name : "Horsea", type : water, stage : 1, clicked : 0, species : "Dragon Site"},
  { name : "Seadra", type : water, stage : 2, clicked : 0, species : "Dragon Site"},
  { name : "Goldeen", type : water, stage : 3, clicked : 0, species : "Goldfish Site"},
  { name : "Seaking", type : water, stage : 4, clicked : 0, species : "Goldfish Site"},
  { name : "Staryu", type : water, stage : 1, clicked : 0, species : "Star Shape Site"},
  { name : "Starmie", type : water, stage : 2, clicked : 0, species : "Mysterious Site"},
  { name : "Mr. Mime", type : psychic, stage : 4, clicked : 0, species : "Barrier Site"},
  { name : "Scyther", type : bug, stage : 4, clicked : 0, species : "Mantis Site"},
  { name : "Jynx", type : psychic, stage : 4, clicked : 0, species : "Human Shape Site"},
  { name : "Electabuzz", type : electric, stage : 5, clicked : 0, species : "Electric Site"},
  { name : "Magmar", type : fire, stage : 5, clicked : 0, species : "Spitfire Site"},
  { name : "Pinsir", type : bug, stage : 5, clicked : 0, species : "Stag Beetle Site"},
  { name : "Tauros", type : normal, stage : 4, clicked : 0, species : "Wild Bull Site"},
  { name : "Magikarp", type : water, stage : 1, clicked : 0, species : "Fish Site"},
  { name : "Gyrados", type : water, stage : 5, clicked : 0, species : "Atrocious Site"},
  { name : "Lapras", type : water, stage : 4, clicked : 0, species : "Transport Site"},
  { name : "Ditto", type : normal, stage : 4, clicked : 0, species : "Transform Site"},
  { name : "Eevee", type : normal, stage : 2, clicked : 0, species : "Evolution Site"},
  { name : "Vaporeon", type : water, stage : 4, clicked : 0, species : "Bubble Jet Site"},
  { name : "Jolteon", type : electric, stage : 4, clicked : 0, species : "Lightning Site"},
  { name : "Flareon", type : fire, stage : 4, clicked : 0, species : "Flame Site"},
  { name : "Porygon", type : normal, stage : 5, clicked : 0, species : "Virtual Site"},
  { name : "Omanyte", type : water, stage : 4, clicked : 0, species : "Spiral Site"},
  { name : "Omastar", type : water, stage : 5, clicked : 0, species : "Spiral Site"},
  { name : "Kabuto", type : rock, stage : 4, clicked : 0, species : "Shellfish Site"},
  { name : "Kabutops", type : rock, stage : 5, clicked : 0, species : "Shellfish Site"},
  { name : "Aerodactyl", type : flying, stage : 5, clicked : 0, species : "Fossil Site"},
  { name : "Snorlax", type : normal, stage : 5, clicked : 0, species : "Sleeping Site"},
  { name : "Articuno", type : ice, stage : 6, clicked : 0, species : "Freeze Site"},
  { name : "Zapdos", type : electric, stage : 6, clicked : 0, species : "Electric Site"},
  { name : "Moltres", type : fire, stage : 6, clicked : 0, species : "Flame Site"},
  { name : "Dratini", type : dragon, stage : 4, clicked : 0, species : "Dragon Site"},
  { name : "Dragonair", type : dragon, stage : 5, clicked : 0, species : "Dragon Site"},
  { name : "Dragonite", type : dragon, stage : 6, clicked : 0, species : "Dragon Site"},
  { name : "Mewtwo", type : psychic, stage : 6, clicked : 0, species : "Genetic Site"},
  { name : "Mew", type : psychic, stage : 7, clicked : 0, species : "New Species Site"}
];